config/routes.rb
Atebitbakery::Application.routes.draw do
  resources :mains

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, :on => :member
  end

  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

def add_product(product_id)
  current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
end

def total_price
  line_items.to_a.sum { |item| item.total_price }
end

def total_items
  line_items.sum(:quantity)
end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  
  def total_price
    product.price * quantity
  end
  
end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price, :stock_quantity, :picture
  validates :name, :presence => true
  
  default_scope :order => 'name'
  
  has_many :line_items
  has_many :orders, :through => :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
      else
        errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true

  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
  
  after_destroy :ensure_an_admin_remains
  
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end

  # 'password' is a virtual attribute
  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        logger.error "Attempt to access invalid cart #{params[:id]}"
        redirect_to store_url, :notice => 'Invalid cart'
      else
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(store_url) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
      session[:cart_id] = nil
      respond_to do |format|
      format.html { redirect_to(store_url) }
      format.xml { head :ok }
      end
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mains }
    end
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
    @main = Main.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @main }
    end
  end

  # GET /mains/new
  # GET /mains/new.json
  def new
    @main = Main.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @main }
    end
  end

  # GET /mains/1/edit
  def edit
    @main = Main.find(params[:id])
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(params[:main])

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: 'Main was successfully created.' }
        format.json { render json: @main, status: :created, location: @main }
      else
        format.html { render action: "new" }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mains/1
  # PUT /mains/1.json
  def update
    @main = Main.find(params[:id])

    respond_to do |format|
      if @main.update_attributes(params[:main])
        format.html { redirect_to @main, notice: 'Main was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main = Main.find(params[:id])
    @main.destroy

    respond_to do |format|
      format.html { redirect_to mains_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
      
  content_tag("div", attributes, &block)
  
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />



			  <title>atebitbakery</title>
         <%= stylesheet_link_tag    "application", :media => "all" %>
          <%= javascript_include_tag "application" %>
          <%= csrf_meta_tags %>

		<link href="style.css" rel="stylesheet" type="text/css" />

			<script src="/assets/jquery.min.js" type="text/javascript"></script>

			<script src="/assets/jquery.tabSlideOut.v1.3.js" type="text/javascript"></script>
      
</head>

<body>

	<div id="menu"><ul>

		<li><a href="Index.htm"><img src="/assets/Home.png" alt="Home"></a></li>
		<li><a href="Concept.htm"><img src="/assets/Concept.png" alt="Concept" /></a></li>
		<li><a href="Shopping.htm"><img src="/assets/Shopping.png" alt="Shopping" /></a></li>
		<li><a href="ShopList.htm"><img src="/assets/ShopList.png" alt="Shop List" /></a></li>
		<li><a href="Blog.htm"><img src="/assets/Blog.png" alt="Blog" /></a></li>
		<li><a href="Contact.htm"><img src="/assets/Contact.png" alt="Contact" /></a></li></ul>

	</div>
        <div id="header">
          
	<div class="logo"></div>
        </div>
	<div class="main">
          	<script type="text/javascript">
		     $(function(){
		         $('.slide-out-div').tabSlideOut({
		             tabHandle: '.handle',
		             pathToTabImage: '/assets/social_tab.png',
		             imageHeight: '98px',
		             imageWidth: '33px',
		             tabLocation: 'left',
		             speed: 500,
		             action: 'click',
		             topPos: '200px',
		             leftPos: '20px',
		             fixedPosition: true,
		         });

		     });

    		</script>
	<div id="innercontent">
            <div id="content">
    <div class="menu">
      <% if session[:user_id] %>  
        <br />
          <%= link_to 'Orders', orders_path %><br />
          <%= link_to 'Products', products_path %><br />
          <%= link_to 'Users', users_path %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete %>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
	<div class="slide-out-div" style="line-height: 1; position: fixed; height: 246px; top: 200px; left: -122px; ">
	            <a class="handle" href="" style="background-image: url(/assets/social_tab.png); background-attachment: initial;
	            background-origin: initial; background-clip: initial; background-color: initial; width: 33px; height: 98px; display: block;
	            text-indent: -99999px; outline-style: none; outline-width: initial; outline-color: initial; position: absolute; top: 0px;
	            right: -33px; background-position: initial initial; background-repeat: no-repeat no-repeat; ">Content</a>
	            <div id="cart">
<% if @cart %>
<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
<%= render @cart %>
<% end %>
<% end %>
</div>
</div>
</div>

 </body>


</html>

app/views/notifier/order_received.text.erb
Dear <%= @order.name %>
Stage Complete! Thanks for your order from atebitbakery.
You ordered the following items:
<%= render @order.line_items %>
The robots will send you an email notification when your order ships.
Have an awesomely nerdy day!

app/views/notifier/order_shipped.text.erb
<h3>atebitbakery Order On The Way</h3>
<p>
Just letting you know that some deliciousness is coming your way:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items %>
</table>